name: Countly C SDK Build Workflow

on:
  push:
    tags:
      - 'v*'


jobs:
  create_release_x64:
    uses: ./.github/workflows/build_arch.yml
    with:
      arch: x64

  create_release_x86:
    uses: ./.github/workflows/build_arch.yml
    with:
      arch: x86

