name: Countly C SDK Build Workflow

on:
  push:
    tags:
      - 'v*'


jobs:
  prepare_arch_independent:
    uses: ./.github/workflows/prepare_arch_independent.yml

  create_release_asset_x64:
    needs: prepare_arch_independent
    uses: ./.github/workflows/build_arch.yml
    with:
      arch: x64

  create_release_asset_x86:
    needs: prepare_arch_independent
    uses: ./.github/workflows/build_arch.yml
    with:
      arch: x86

