name: Workflow to build assets for a single architecture
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      release_upload_url:
        required: true
        type: string

jobs:
  create_arch_release:
    name: Create Release Asset for ${{ inputs.arch }}
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Generate project files
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_GENERATOR_PLATFORM=${{ (inputs.arch=='x86' && 'Win32') || 'x64' }} ..

      - name: Build project
        working-directory: build
        run: cmake --build . --config Release

      - name: Create release archive
        working-directory: build
        run: |
          mkdir relarchive
          copy Release\countly.dll relarchive
          copy Release\countly.lib relarchive
          copy Release\countly.pdb relarchive
          copy ..\include\countly_c.h relarchive
          cd relarchive
          Compress-Archive -Path . -DestinationPath ..\countly_${{ inputs.arch }}.zip

      - name: Upload Release Asset (${{ inputs.arch }})
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_upload_url }}
          asset_path: build/countly_${{ inputs.arch }}.zip
          asset_name: countly_${{ inputs.arch }}.zip
          asset_content_type: application/zip

