name: Countly C SDK Build Workflow for a single architecture
on:
  workflow_call:
  

jobs:
  prepare_arch_independent:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Github Release
        id: create_github_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated Release by GitHub Action CI
          draft: false
          prerelease: true

